version: '3.9'

services:
  db:
    build: ./DataBase
    container_name: DataBase
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - devnet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devuser -d devdb"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  back:
    build: ./Site
    container_name: Site
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: devuser
      DB_PASSWORD: devpass
      DB_NAME: devdb
    ports:
      - "3000:3000"
    volumes:
      - ./Site:/app
      - /app/node_modules
    networks:
      - devnet
    command: ["npm", "run", "dev"]

  pgadmin:
    build: ./Graphical_Interface 
    container_name: Graphical_Interface 
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5050:80"
    networks:
      - devnet

volumes:
  db_data:

networks:
  devnet:
