version: '3.9'

services:
  db:
    build: ./db
    container_name: postgres_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - devnet

  back:
    build: ./back
    container_name: node_backend
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: devuser
      DB_PASSWORD: devpass
      DB_NAME: devdb
    ports:
      - "3000:3000"
    volumes:
      - ./back:/app
      - /app/node_modules
    networks:
      - devnet

  pgadmin:
    build: ./pgadmin
    container_name: pgadmin
    depends_on:
      - db
    ports:
      - "5050:80"
    networks:
      - devnet

volumes:
  db_data:

networks:
  devnet:
