version: '3.9'

services:
  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: devdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql:ro
    networks:
      - devnet

  back:
    build: ./back
    container_name: node_backend
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: devuser
      DB_PASSWORD: devpass
      DB_NAME: devdb
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - ./back:/app    
      - /app/node_modules             
    networks:
      - devnet
    command: sh -c "npm install && npm run dev"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: augustin.viemont@epitech.eu
      PGADMIN_DEFAULT_PASSWORD: viemont
    ports:
      - "5050:80"
    networks:
      - devnet
    depends_on:
      - db

volumes:
  db_data:

networks:
  devnet:
